benchmark:
  id: 1d
  version: 1
data:
- name: run_time
  values:
  - sim_time: 1938427.8409117
    wall_time: 5520
- name: memory_usage
  transform:
  - expr: datum.value_g * 1048576.0
    field: value
    type: formula
  values:
  - unit: GB
    value_g: 3.57
- format:
    parse:
      TotalEnergy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - expr: datum.TotalEnergy
    field: free_energy
    type: formula
  - test: datum.time > 1
    type: filter
  - test: datum.time < 1e6
    type: filter
  url: https://gist.githubusercontent.com/wd15/41e21ea1090057c42a59380d90367763/raw/a211864b3269e86eb63db6f3dd9167ed18b92d08/hackathon_p1_sphere_IA.csv
metadata:
  author: A. M. Jokisaari
  email: andrea.jokisaari@northwestern.edu
  github_id: ''
  hardware:
    cores: 20
    details:
    - name: processor
      values: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GH
  implementation:
    end_condition: Equilibrium, total energy fluctuated due to numerical noise
    repo:
      url: https://bitbucket.org/ajokisaari/coral
      version: e8fc74f
  software:
    details:
    - name: time stepper
      values: IA
    name: moose
    version: Hedgehog (now Coral)
  summary: Information for the Benchmark1 problems
  timestamp: 6/28/2016
