---
benchmark:
  id: 1a

metadata:
  # Describe the runtime environment
  summary: Serial Travis CI benchmark with FiPy, periodic domain
  author: Trevor Keller
  email: trevor.keller@nist.gov
  date: Tue, 10 Jan 2017 00:46:24 +0000
  hardware:
    # Required hardware details
    architecture: x86_64
    cores: 1
    # Optional hardware details
    details:
      - name: clock
        value: 2300.000
        units: MHz
  software:
    name: fipy
    url: https://github.com/usnistgov/fipy
    version: 3.1
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: 3.1.2.dev137+g5fcf04e
      branch: develop
  implementation:
    end_condition: time limit, Travis CI runs die after 50 minutes total
    repo:
      url: https://github.com/usnistgov/FiPy-spinodal-decomposition-benchmark/tree/master/periodic/
      version: 944284638f00c3a411a71981d27becf97a2eb0e4
      branch: master
      badge: https://travis-ci.org/usnistgov/FiPy-spinodal-decomposition-benchmark.svg?branch=master
    details:
      - name: mesh
        value: uniform rectilinear
      - name: numerical_method
        value: finite volume

data:
  # Gather simulation output
  - name: free_energy
    # JSON list of {time, energy} pairs
    values: [{"energy": 319.06303925368354, "time": 0.0}, {"energy": 164.2216014340151, "time": 49.02613779824095}, {"energy": 131.98219930377076, "time": 108.35512414140523}, {"energy": 122.72687849230819, "time": 163.45883181339772}, {"energy": 115.84448550680348, "time": 219.35317030457253}, {"energy": 111.5408433711128, "time": 273.360149663156}, {"energy": 107.92440125854729, "time": 326.6283721598183}, {"energy": 104.19038700542657, "time": 381.73462920548144}, {"energy": 100.9592325038704, "time": 435.6374245617747}, {"energy": 98.55448703132164, "time": 487.51762396301325}]
  - name: run_time
    values: {'time': 1495.47, 'unit': seconds}
  - name: memory_usage
    values: {'value': 470976, 'unit': KB}

