_id: ebf28910-1259-11e8-936c-053a4ee5c3bb
metadata:
  author:
    first: Stephen
    last: DeWitt
    email: stvdwtt@umich.edu
    github_id: stvdwtt
  timestamp: '7 February, 2018'
  summary: >-
    Initial run of Benchmark 7 using PRISMS-PF. This simulation uses linear
    elements (2nd order accurate in space) and forward Euler time stepping (1st
    order in time).
  implementation:
    name: PRISMS-PF
    repo:
      url: >-
        https://github.com/prisms-center/phaseField/tree/master/applications/CHiMaD_benchmark7
      version: 7cdde5a5c48ef64b6a9d2454836ce3c784f222a5
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '3.5'
    cores: '6'
    nodes: '1'
benchmark:
  id: 7a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '0'
        sim_time: '0'
  - name: memory_usage
    values:
      - unit: KB
        value: '0'
  - name: spatial_linear
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm7a_spatial_linear.csv'
    format:
      type: csv
      parse:
        mesh_size: number
        L2_error: number
    description: >-
      Spatial convergence test using quadratic elements. The time step is
      constant at 2e-4 for all simulations. The order of accuracy is higher than
      expected for unknown reasons.
    type: line
    transform:
      - type: formula
        expr: datum.mesh_size
        as: x
      - type: formula
        expr: datum.L2_error
        as: 'y'
  - name: temporal_linear
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm7a_temporal_linear.csv'
    format:
      type: csv
      parse:
        time_step: number
        L2_error: number
    description: "Temporal convergence test using quadratic elements. The mesh size is constant at 0.015625 for all simulations.\r\n\r\nThe order of accuracy is much lower than expected (the expected value is 1.0). This is because the maximum stable time step decreases with the mesh spacing, such that the spatial discretization error always is a large portion of the total error."
    type: line
    transform:
      - type: formula
        expr: datum.time_step
        as: x
      - type: formula
        expr: datum.L2_error
        as: 'y'
date: 1518703805
