---
benchmark:
  id: 1a
  version: 1

metadata:
  # Describe the runtime environment
  summary: Parallel Travis CI benchmark with MMSP, periodic domain
  author: Trevor Keller
  email: trevor.keller@nist.gov
  timestamp: Mon, 09 Jan 2017 20:05:21 -0500
  hardware:
    # Required hardware details
    architecture: x86_64
    cores: 12
    # Optional hardware details
    details:
      - name: clock
        values: 3.5
        # unit: GHz
  software:
    name: mmsp
    version: "4"
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: "8f29eb47146b9fbbdcd17b08d12e06fceb3ed728"
  implementation:
    end_condition: time limit, should asymptote toward steady-state beyond t=100000
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/periodic/
      version: "c51089f860f70d4e3d77881875d024ee4c01c409"
    details:
      - name: mesh
        values: uniform rectilinear
      - name: numerical_method
        values: explicit finite difference
      - name: compiler
        values: GNU mpic++
      - name: parallel_model
        values: MPI

data:
  # Gather simulation output
  - name: timestep
    values: 0.00195312
  - name: free_energy
    url: https://cdn.rawgit.com/tkphd/8659310fb61efba6c97df42e12382924/raw/de90f8048f72c2abdf579987d87fa152701de397/mmsp_1a_wrksttn.json
    format:
      type: json
    transform:
      - type: filter
        test: "datum.time > 0.01"
      - type: formula
        field: free_energy
        expr: datum.energy
  - name: run_time
    values:
      [
        {
          "time": 232301.41,
          "sim_time": 100000
        }
      ]
  - name: memory_usage
    values:
      [
        {
          "value": 27840,
          "unit": KB
        }
      ]
