---
  benchmark:
    id: 1c
    version: 1

  metadata:
    summary: Metadata for the Benchmark1 problems
    timestamp: 02/20/2017
    author: PC. Simon
    email: pjs5523@psu.edu
    timestamp: "Mon Feb  6 19:47:34 EST 2017"
    software:
      name: moose
      version: git commit 2593a61 on 2017-01-18
    hardware:
      architecture: x86_64
      cores: 60
      details:
        - name: clock rate
          values:
            rate:
            unit: GHz
        - name: processor
          values: ""
    implementation:
      repo:
        url: https://github.com/simopier/CHiMaD/blob/master/H5.i
        version: 724999206
      end_condition: Equilibrium, total energy fluctuated due to numerical noise
      details:
        - name: time_stepper
          values: IA

  data:
    - name: run_time
      values:
        [
          {
            "time": 6850,
          }
        ]
      transform:
        - type: formula
          field: value
          expr: datum.value_m * 1024.0
    - name: free_energy
      url: https://gist.githubusercontent.com/simopier/739e1e4cb6e3682badee62dbb242fd98/raw/ec506181dfd410da88ca3760fd800fe930e48338/moose_psu_1c_IA.csv
      format:
        type: csv
        parse:
          f_density: number
          time: number
      transform:
        - type: formula
          field: free_energy
          expr: datum.free_energy
        - type: filter
          test: "datum.time > 0.01"
