benchmark:
  id: 2b
  version: 1
data:
- name: run_time
  values:
  - sim_time: 100000
    wall_time: 7180
- name: memory_usage
  values:
  - unit: MB
    value: 1664
- format:
    parse:
      total_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.total_energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/78424733cb6f3a1379ec55fe49d64b00/raw/aa3918c8e919dd1379bbb54746e60992430553de/MOOSE_FH_2b.csv
  author:
    email: fhilty@ufl.edu
    first: F.
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 8
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/2b.i
      version: a001b86
  summary: Metadata for the Benchmark 2b
timestamp: 8/9/18
