---
  benchmark:
    id: 1d
    version: 1

  metadata:
    summary: Metadata for the Benchmark1 problems
    timestamp: 02/20/2017
    author: PC. Simon
    email: pjs5523@psu.edu
    timestamp: "Tue Feb  7 10:36:59 EST 2017"
    software:
      name: moose
      version: git commit 2593a61 on 2017-01-18
    hardware:
      architecture: x86_64
      cores: 100
      details:
        - name: clock rate
          values:
            rate:
            unit: GHz
        - name: processor
          values: ""
    implementation:
      repo:
        url: https://github.com/simopier/CHiMaD/blob/master/H8.i
        version: "724999206"
      end_condition: Time limit (3000000)
      details:
        - name: time_stepper
          values: STA

  data:
    - name: run_time
      values:
        [
          {
            "time": 99851,
            "sim_time": 3000000
          }
        ]
      transform:
        - type: formula
          field: value
          expr: datum.value_m * 1024.0
    - name: memory_usage
      values:
        value: 100
        unit: GB
    - name: free_energy
      url: https://gist.githubusercontent.com/simopier/739e1e4cb6e3682badee62dbb242fd98/raw/ec506181dfd410da88ca3760fd800fe930e48338/moose_psu_1d_STA.csv
      format:
        type: csv
        parse:
          f_density: number
          time: number
      transform:
        - type: formula
          field: free_energy
          expr: datum.f_density
        - type: filter
          test: "datum.time > 0.01"
