_id: f79e7a70-18d1-11e8-81e7-ad1d9008e648
metadata:
  author:
    first: Narut
    last: Sereewattanawoot
    email: narut.se@gmail.com
    github_id: narutse
  timestamp: '23 February, 2018'
  summary: "Spatial convergence analysis for the benchmark problem 1a.\r\nThe clock time is recorded across all runs combined."
  implementation:
    name: tester/FBEspace.cpp
    repo:
      url: 'https://github.com/narutse/phasefield'
      version: 6175566e63946af7a2ac8f0ca44e2b0cddc0b7ff
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: non-gpu
    parallel_model: serial
    clock_rate: '4.6'
    cores: '1'
    nodes: '1'
benchmark:
  id: 7a
  version: '0'
data:
  - name: run_time
    values:
      - wall_time: '17986'
        sim_time: '17985.32'
  - name: memory_usage
    values:
      - unit: KB
        value: '1229176'
  - name: spatial
    url: 'https://gist.githubusercontent.com/wd15/c7cbecda6798c9a1cbecedf5fabea7dd/raw/cc87e95b1c7f770fcaa02468f09659018d1258b6/gistfile1.txt'
    format:
      type: csv
      parse:
        grid: number
        L2: number
    description: csv formatted as specified in the benchmark problem
    type: line
    transform:
      - type: formula
        expr: datum.grid
        as: x
      - type: formula
        expr: datum.L2
        as: 'y'
  - name: FBEspace
    url: 'https://raw.githubusercontent.com/narutse/phasefield/master/plots/FBEspace.png'
    type: image
    description: 'loglog plot '
date: 1519415072
