---
benchmark:
  id: 1b

metadata:
  # Describe the runtime environment
  summary: MPI parallel workstation benchmark with MMSP, no-flux domain
  author: Trevor Keller
  email: trevor.keller@nist.gov
  date: Mon, 09 Jan 2017 19:21:38 +0000
  hardware:
    # Required hardware details
    architecture: x86_64
    cores: 2
    # Optional hardware details
    details:
      - name: clock
        value: 2300.000
        units: MHz
  software:
    name: mmsp
    url: https://github.com/mesoscale/mmsp
    version: 4
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: 8f29eb47146b9fbbdcd17b08d12e06fceb3ed728
      branch: develop
  implementation:
    end_condition: time limit (Travis CI dies after 10 min of no CLI output)
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/no-flux/
      version: 639633660d76293556747f3cdde83034b3abc2a5
      branch: master
      badge: https://travis-ci.org/mesoscale/MMSP-spinodal-decomposition-benchmark.svg?branch=master
    details:
      - name: mesh
        value: uniform rectilinear
      - name: numerical_method
        value: explicit finite difference
      - name: compiler
        value: GNU mpic++
      - name: parallel_model
        value: MPI

data:
  # Gather simulation output
  - name: timestep
    value: 0.00195312
  - name: free_energy
    # JSON list of {time, energy} pairs
    values: [{"time":0, "energy":319.045}, {"time":19.5312, "energy":311.972}]
  - name: run_time
    values: {'time': 295.25, 'unit': seconds}
  - name: memory_usage
    values: {'value': 33096, 'unit': KB}

