---
benchmark:
  id: 1b

metadata:
  # Describe the runtime environment
  summary: Travis CI benchmark with MMSP, no-flux domain
  author: Trevor Keller
  email: trevor.keller@nist.gov
  date: Tue, 10 Jan 2017 01:20:43 +0000
  hardware:
    # Required hardware details
    architecture: x86_64
    cores: 2
    # Optional hardware details
    details:
      - name: clock
        value: 2300.000
        units: MHz
  software:
    name: mmsp
    url: https://github.com/mesoscale/mmsp
    version: 4
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: 8f29eb47146b9fbbdcd17b08d12e06fceb3ed728
      branch: develop
  implementation:
    end_condition: time limit, Travis CI runs die after 50 minutes total
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/no-flux/
      version: 05a5db5111d92b916d51e143adf068547c3a654d
      branch: master
      badge: https://api.travis-ci.org/mesoscale/MMSP-spinodal-decomposition-benchmark.svg?branch=master
    details:
      - name: mesh
        value: uniform rectilinear
      - name: numerical_method
        value: explicit finite difference
      - name: compiler
        value: GNU mpic++
      - name: parallel_model
        value: MPI
data:
  # Gather simulation output
  - name: timestep
    value: 0.00195312
  - name: free_energy
    # JSON list of {time, energy} pairs
    values: [{"time":0, "energy":319.045}, {"time":7.61719, "energy":318.155}, {"time":15.2344, "energy":315.555}, {"time":22.8516, "energy":307.135}, {"time":30.4688, "energy":283.973}, {"time":38.0859, "energy":242.644}, {"time":45.7031, "energy":214.109}, {"time":53.3203, "energy":205.499}, {"time":60.9375, "energy":200.944}, {"time":68.5547, "energy":196.86}, {"time":76.1719, "energy":192.77}]
  - name: run_time
    values: {'time': 1142.51, 'unit': seconds}
  - name: memory_usage
    values: {'value': 33844, 'unit': KB}

