benchmark:
  id: 1c
  version: 1
data:
- name: run_time
  values:
  - sim_time: 1000000
    wall_time: 846
- name: memory_usage
  values:
  - unit: MB
    value: 1530
- format:
    parse:
      total_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.total_energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/35ae4be430a98a5f3e9ed3b3fdb50bb6/raw/78a8e3402c9b8c091343e8534a1e7dc56c3c6c78/MOOSE_FH_1c.csv
  author:
    email: fhilty@ufl.edu
    first: F.
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 8
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/1c.i
      version: a001b86
  summary: Metadata for the Benchmark 1c
timestamp: 8/9/18
