---
benchmark_id: 1a

metadata:
  summary: Fake metadata for the Benchmark1 problems
  timestamp: 6/28/2016
  author: A. M. Jokisaari
  software:
    name: moose
    version: Hedgehog (now Coral)
  hardware:
    cores: 6
    details:
      - name: clock rate
        values:
          rate: 2.70
          unit: GHz
      - name: processor
        values: "Intel(R) Core(M) i7-6820HQ CPU @ 2.70GHz"
  implementation:
    repo:
      url: https://bitbucket.org/ajokisaari/coral
      version: e8fc74f
    end_condition: Equilibrium, total energy fluctuated due to numerical noise
    details:
      - name: time_stepper
        values: IA

data:
  - name: run time
    values: 62 minutes
  - name: memory usage
    values: 796 MB
  - name: free_energy
    url: https://gist.githubusercontent.com/wd15/41e21ea1090057c42a59380d90367763/raw/6cdc4a241f133355a2f0f0691fc96206ef3fa29a/hackathon_p1_square_NF_IA.csv
    format:
      type: csv
      parse:
        TotalEnergy: number
        time: number
    transform:
      - type: formula
        field: free_energy
        expr: "datum.TotalEnergy * 3."
      - type: filter
        test: "datum.free_energy < 400.0"
      - type: filter
        test: "datum.time > 0.01"
