# CHiMaD Phase-Field simulation submission
# minimal example: every line is required,
# comments (prefixed by '#') are optional.

---  # tag start of YAML block

benchmark:  # Refer to the problem definition for appropriate values
  id: 1a  # number+letter
  version: 1  # number

metadata:  # Describe the runtime environment, hardware and software
  summary: concise description of this contribution
  author: Given and Surname
  email: alias@organization.com
  timestamp: Mon, 10 Mar 1982 15:03:32 -0500  # 'date -R' on Linux or any valid timestamp
  hardware:  # relevant details of your machine or cluster
    cores: 6  # number actually used if less than total available
  software:  # software framework your application is built upon
    name: fipy  # all lower-case, e.g. fipy or moose or prisms, etc.

data:  # Use Vega data standard, https://vega.github.io/vega-lite/docs/data.html
  - name: free_energy  # for GitHub Gist data, provide URL from "raw" link
    url: https://somewhere/data.csv
    format:
      type: csv
      parse:
        free_energy: number
        time: number
    transform:  # eliminate zero for logarithmic time-axis scaling
      - type: filter
        test: "datum.time > 0.01"
  - name: run_time  # seconds elapsed when final simulation-time was reached
    values:
      [
        {
          "sim_time": 53333.3,
          "time": 170618.87
        }
      ]
  - name: memory_usage  # peak memory used by the whole cluster
    values:
      [
        {
          "value": 27232,
          "unit": KB
        }
      ]
