---
benchmark:
  id: 2c
  version: 1

metadata:
  summary: Metadata for the Benchmark2 problems
  timestamp: 6/28/2016
  author: A. M. Jokisaari
  email: andrea.jokisaari@northwestern.edu
  software:
    name: moose
    version: Hedgehog (now Coral)
  hardware:
    cores: 6
    details:
      - name: clock rate
        values:
          rate: 2.70
          unit: GHz
      - name: processor
        values: "Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz"
  implementation:
    repo:
      url: https://bitbucket.org/ajokisaari/coral
      version: e8fc74f
    end_condition: Equilibrium, total energy fluctuated due to numerical noise
    details:
      - name: time_stepper
        values: STA

data:
  - name: run_time
    values:
      - wall_time: 5580
        sim_time: 0
        unit: s
  - name: memory_usage
    values:
      value: 477
      unit: MB
  - name: free_energy
    url: https://gist.githubusercontent.com/wd15/41e21ea1090057c42a59380d90367763/raw/eba1e44ec25a2d9a906b2c802596778892b2f676/hackathon_p2_tshape_STA_dfdt.csv
    format:
      type: csv
      parse:
        TotalEnergy: number
        time: number
    transform:
      - type: formula
        field: free_energy
        expr: datum.TotalEnergy
      - type: filter
        test: "datum.time > 0.01"
