benchmark:
  id: 1b
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '200000'
    wall_time: '7464'
- name: memory_usage
  values:
  - unit: KB
    value: '308224'
- description: free energy data
  format:
    parse:
      free_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/tkphd/c4523570be7a1615de36f40660d7d4e0/raw/6bc40070d456572881d565e788781048590e72f3/hiperc-cuda-spinodal.csv
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: '1.48'
    cores: '1792'
    cpu_architecture: x86_64
    nodes: 1
    parallel_model: threaded
  implementation:
    container_url: ''
    name: custom
    repo:
      url: https://github.com/usnistgov/hiperc
      version: b25b14acda7c5aef565cdbcfc88f2df3412dcc46
  simulation_name: HiPerC_CUDA
  summary: HiPerC spinodal decomposition result using CUDA on a Tesla P100
  timestamp: 18 December, 2017
