metadata:
  github_id: tkphd
  author:
    first: Trevor
    last: Keller
  email: trevor.keller@nist.gov
  simulation_name: HiPerC_CUDA
  summary: HiPerC spinodal decomposition result using CUDA on a Tesla P100
  timestamp: '18 December, 2017'
  implementation:
    repo:
      url: 'https://github.com/usnistgov/hiperc'
      version: b25b14acda7c5aef565cdbcfc88f2df3412dcc46
  hardware:
    architecture: x86_64
    parallel_model: threaded
    clock_rate: '1.48'
    cores: '1792'
  software:
    name: custom
    version: alpha
benchmark:
  id: 1b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '7464'
        sim_time: '200000'
  - name: memory_usage
    values:
      - unit: KB
        value: '308224'
  - name: free_energy
    type: line
    url: >-
      https://gist.githubusercontent.com/wd15/a716010583baae7266bd7bb4b272212a/raw/a5d110e2e1d6ed0c4a0f7c97e6ff7891f1e1c946/bkah.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    description: free energy data
    transform:
      - as: y
        expr: datum.free_energy
        type: formula
      - as: x
        expr: datum.time
        type: formula
