_id: 678e1800-e433-11e7-8b3a-bb1b96b9aa20
metadata:
  author: Trevor Keller
  email: trevor.keller@nist.gov
  simulation_name: HiPerC_CUDA
  summary: HiPerC spinodal decomposition result using CUDA on a Tesla P100
  timestamp: '18 December, 2017'
  implementation:
    repo:
      url: 'https://github.com/usnistgov/hiperc'
      version: b25b14acda7c5aef565cdbcfc88f2df3412dcc46
    container_url: ''
  hardware:
    architecture: x86_64
    parallel_model: threaded
    clock_rate: '1.48'
    cores: '1792'
    nodes: '1'
  software:
    name: custom
    version: alpha
    repo:
      url: 'https://github.com/usnistgov/hiperc'
      version: b25b14acda7c5aef565cdbcfc88f2df3412dcc46
benchmark:
  id: 1b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '7464'
        sim_time: '200000'
  - name: memory_usage
    values:
      - unit: KB
        value: '308224'
  - name: free_energy
    url: >-
      https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/free-energy.csv
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    transform:
      - type: filter
        test: datum.time > 0.01
  - name: cut_plane_x
    url: ''
    format:
      parse:
        x: number
        concentration: number
      type: csv
  - name: cut_plane_y
    url: ''
    format:
      parse:
        'y': number
        concentration: number
      type: csv
date: 1513629509
timestamp: 1513629509
