_id: 3a137180-168e-11e8-b1fd-f167a257a673
metadata:
  author:
    first: Stephen
    last: DeWitt
    email: stvdwtt@umich.edu
    github_id: stvdwtt
  timestamp: '1 February, 2018'
  summary: >-
    Initial run of Benchmark 7 using PRISMS-PF. This simulation uses quadratic
    elements (3rd order accurate in space) and forward Euler time stepping (1st
    order in time).
  implementation:
    name: prisms
    repo:
      url: >-
        https://github.com/prisms-center/phaseField/tree/master/applications/CHiMaD_benchmark7
      version: 7cdde5a5c48ef64b6a9d2454836ce3c784f222a5
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '3.5'
    cores: '6'
    nodes: '1'
benchmark:
  id: 7b
  version: '0'
data:
  - name: run_time
    values:
      - wall_time: '0'
        sim_time: '0'
  - name: memory_usage
    values:
      - unit: KB
        value: '0'
  - name: cost
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm7b_quad.csv'
    format:
      type: csv
      parse:
        error: number
        cost: number
    description: Error vs Cost plot
    type: line
    transform:
      - type: formula
        expr: datum.error
        as: x
      - type: formula
        expr: datum.cost
        as: 'y'
  - name: time
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm7b_quad.csv'
    format:
      type: csv
      parse:
        error: number
        wall_time: number
    description: Error vs Time plot
    type: line
    transform:
      - type: formula
        expr: datum.error
        as: x
      - type: formula
        expr: datum.wall_time
        as: 'y'
date: 1519166075
approved: false
title: Comment
