width: 400
height: 200
axes:
  - type: x
    scale: x
  - type: y
    scale: y
scales:
  - name: x
    nice: true
    type: linear
    range: width
    domain:
      data: table
      field: data.time
  - name: y
    nice: true
    type: linear
    range: height
    domain:
      data: table
      field: data.free_energy
marks:
  - type: line
    from:
      data: moose_1a_ia
    properties:
      enter:
        x:
          scale: x
          field: data.time
        y:
          scale: y
          field: data.free_energy
        stroke:
          value: steelblue
        strokeWidth:
          value: 1
        strokeOpacity:
          value: 1.0
