benchmark:
  id: 2c
  version: 1
data:
- name: run_time
  values:
  - sim_time: 100000
    wall_time: 38361
- name: memory_usage
  values:
  - unit: MB
    value: 3881
- format:
    parse:
      total_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.total_energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/0bcacc0c7753c560f2d145dbb491fbb0/raw/c4a619032e32157bdb1d71e46c5cbd7c08fd03ca/MOOSE_FH_2c.csv
  author:
    email: fhilty@ufl.edu
    first: F.
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 8
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/2c.i
      version: a001b86
  summary: Metadata for the Benchmark 2c
timestamp: 8/9/18
