---
benchmark:
  id: 1b
  version: 1

metadata:
  # Describe the runtime environment
  summary: MPI parallel workstation benchmark with MMSP, no-flux domain
  author: Trevor Keller
  email: trevor.keller@nist.gov
  timestamp: Sun, 12 Feb 2017 09:16:30 -0500
  hardware:
    # Required hardware details
    architecture: x86_64
    cores: 12
    # Optional hardware details
    details:
      - name: clock
        values: 3.8
        # unit: GHz
  software:
    name: mmsp
    version: "5.2"
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: "2352cdf62c6db99f6644d88a0c2f9917d2d1882f"
  implementation:
    end_condition: sim time greater than 50000 (51200000 timesteps)
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/no-flux/
      version: "4c3af04ac4e46665eacc599b0d2cc8b4a9963461"
      # badge: https://api.travis-ci.org/mesoscale/MMSP-spinodal-decomposition-benchmark.svg?branch=master
    details:
      - name: mesh
        values: uniform rectilinear
      - name: numerical_method
        values: explicit finite difference
      - name: compiler
        values: GNU mpic++
      - name: parallel_model
        values: MPI

data:
  # Gather simulation output
  - name: timestep
    values: 0.00104167
  - name: free_energy
    url: https://gist.githubusercontent.com/tkphd/8659310fb61efba6c97df42e12382924/raw/98fcbed6c526092ec561dc11904c3754ccbfd880/mmsp_1b_wrksttn.csv
    format:
      type: csv
      parse:
        time: number
        free_energy: number
    transform:
      - type: filter
        test: "datum.time > 0.01"
  - name: run_time
    values:
      [
        {
          "sim_time": 53333.3,
          "time": 170618.87 # seconds
        }
      ]
  - name: memory_usage
    values:
      [
        {
          "value_per": 28492,
          "unit": KB
        }
      ]
    transform:
      - type: formula
        value: 12*value_per

