benchmark:
  id: 2d
  version: 1
data:
- name: run_time
  values:
  - sim_time: 100000
    wall_time: 36195
- name: memory_usage
  values:
  - unit: MB
    value: 5404
- format:
    parse:
      total_energy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.total_energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/28416774cdb0401c3b901c59350215b2/raw/7acad7bc794ba7b00f6fcc9f87c269ab9265cb9a/MOOSE_FH_2d.csv
  author:
    email: fhilty@ufl.edu
    first: F.
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 8
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/2d.i
      version: a001b86
  summary: Metadata for the Benchmark 2d
timestamp: 8/9/18
