---
benchmark:
  id: 1c

metadata:
  # Describe the runtime environment
  summary: MPI parallel workstation benchmark with MMSP, T-shape domain
  author: Trevor Keller
  email: trevor.keller@nist.gov
  date: Mon, 09 Jan 2017 19:26:39 +0000
  hardware:
    # Required hardware details
    architecture: x86_64
    cores: 2
    # Optional hardware details
    details:
      - name: clock
        value: 2300.000
        units: MHz
  software:
    name: mmsp
    url: https://github.com/mesoscale/mmsp
    version: 4
    repo:
      url: https://github.com/mesoscale/mmsp/tree/develop
      version: 8f29eb47146b9fbbdcd17b08d12e06fceb3ed728
      branch: develop
  implementation:
    end_condition: time limit (Travis CI dies after 10 min of no CLI output)
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/T-shape/
      version: 639633660d76293556747f3cdde83034b3abc2a5
      branch: master
      badge: https://travis-ci.org/mesoscale/MMSP-spinodal-decomposition-benchmark.svg?branch=master
    details:
      - name: mesh
        value: uniform rectilinear
      - name: numerical_method
        value: explicit finite difference
      - name: compiler
        value: GNU mpic++
      - name: parallel_model
        value: MPI

data:
  # Gather simulation output
  - name: timestep
    value: 0.00195312
  - name: free_energy
    # JSON list of {time, energy} pairs
    values: [{"time":0, "free_energy":31.8815}, {"time":19.5312, "free_energy":30.7252}]
  - name: run_time
    values: {'time': 50.36, 'unit': seconds}
  - name: memory_usage
    values: {'value': 32660, 'unit': KB}

